version: '3'
services:
    web:
        build: ./django
	command: python manage.py runserver 0.0.0.0:8000
	restart: always
	volumes:
	    - api_data:/docker_api
	ports:
	    - "80:8000"
volumes:
    api_data:
