version: '3'
services:
    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - api_data:/docker_api
            - ./log:/var/log/nginx
        depends_on:
            - api
    mysql:
        container_name: mysql-container
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysqldb:/var/lib/mysql
        depends_on:
            - api
        command: ["mysqld", "--character-set-server=utf8"]
        ports:
            - "3306:3306"
    api:
        container_name: api-container
        build: ./django
        command: uwsgi --ini uwsgi.ini
        restart: always
        volumes:
            - api_data:/docker_api
        ports:
            - "8000:8000"
volumes:
    api_data:
    mysqldb:
